### ISSUE TITLE
Broken Texture 

### ISSUE THREAD

**Issue by bambangtales** [masagrator/SPRB-ENX#2]
SFIGHT_CHARACTER_SELECT_OPTION_BG.dat at OTHCG folder
![file](https://user-images.githubusercontent.com/68832156/203489562-dc5c8f9a-b44a-4a3c-853d-e8c2e293788e.jpg)

Also at the Flower Field monologue scene (blue italic fonts). I don't know which file, but apparently in EVENTCG folder.

**Comment by masagrator** [comment]
Ok, fixed issue with other repo and now I have time for you. :D 

Can you upload SFIGHT_CHARACTER_SELECT_OPTION_BG.dat **_DIRECTLY_** from your sdcard here? Pack it to zip otherwise github won't accept it. Don't upload any file that is already on your PC.

**Comment by masagrator** [comment]
This should fix all textures.

https://github.com/masagrator/SPRB-ENX/releases/tag/1.0.2
